package gurumirum.sad.app

import gurumirum.sad.VERSION
import org.intellij.lang.annotations.Language

@Language(value = ".sad.kts")
val DEFAULT_CONFIG: String = """/*
GENERATED BY: SAD $VERSION
Repository: https://github.com/gurumirum/sad
Online Docs: https://github.com/gurumirum/sad/wiki
 */
"""